apiVersion: v1
kind: Secret
metadata:
  name: backstage-secrets
  namespace: backstage
type: Opaque
data:
  GITHUB_TOKEN: ""
  # Uncomment when Azure SSO credentials are available
  # AUTH_MICROSOFT_CLIENT_ID: ""
  # AUTH_MICROSOFT_CLIENT_SECRET: ""
  # AUTH_MICROSOFT_TENANT_ID: ""
